version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.09
      - image: circleci/python:3.8  # Ganti dengan image yang sesuai
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Verify Node.js and npm Versions
          command: |
            node -v
            npm -v
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - run:
          name: Install Node.js Dependencies
          command: npm install
      # Code style
      - run:
          name: Run Lint Style
          command: npm run lint
      # Code coverage
      - run:
          name: Run Tests Coverage
          command: npm test -- --coverage
      # Vulnerability 
      - run:
          name: Install Snyk
          command: npm install -g snyk
      - run:
          name: Run Snyk Test Vulnerability 
          command: snyk test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
