version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: cimg/android:2024.09
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Verify Java Version
          command: java -version
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

  code_coverage:
    docker:
      - image: cimg/android:2024.09
    executor: android/android
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Tests with Coverage
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports/coverage
          destination: coverage-reports

  check_style:
    docker:
      - image: cimg/android:2024.09
    executor: android/android
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Check Code Style
          command: ./gradlew ktlintCheck
      - store_artifacts:
          path: app/build/reports/checkstyle
          destination: checkstyle-reports

  vulnerability_analysis:
    docker:
      - image: cimg/android:2024.09
    executor: android/android
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Vulnerability Analysis
          command: ./gradlew dependencyCheckAnalyze || true  # Always succeed
      - store_artifacts:
          path: app/build/reports/dependency-check-report
          destination: vulnerability-reports
    timeout: 5m  # Set a timeout duration (e.g., 5 minutes)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - code_coverage:
          requires:
            - build
      - check_style:
          requires:
            - build
      - vulnerability_analysis:
          requires:
            - build
